# Generated by Django 4.1.2 on 2022-10-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_users_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='last_name',
            new_name='surname',
        ),
    ]
